(#143) Add support npm version --git-tag-version argument
cake-contrib/Cake.Npm pull request #144
Opened 2023-06-23 07:50 UTC by eoehen

2023-06-23 21:36 UTC, pascalberger requested changes
@eoehen  Thanks for the pull request. I added one comment how it can be implemented to be more aligned with npm command line option.

2023-06-23 21:36 UTC, pascalberger commented on src/Cake.Npm/BumpVersion/NpmBumpVersionSettings.cs
> +        public bool NoGitTagVersion { get; set; }
To make it easier to understand for the user we should use the same name as the npm command has (`GitTagVersion`) and make it nullable: If not defined `git-tag-version` won't be added and default value as defined by the npm command is used, if set `git-tag-version` is added with the corresponding value.

2023-06-26 09:27 UTC, eoehen commented
@pascalberger 
Since rebasing, I can no longer run cake build locally.
![image](https://github.com/cake-contrib/Cake.Npm/assets/49316770/f71dc670-cb58-4c09-82f3-fd8b1c7cb486)
Do you have any idea what this could be?

2023-06-26 09:47 UTC, pascalberger commented
> @pascalberger Since rebasing, I can no longer run cake build locally. ![image](https://user-images.githubusercontent.com/49316770/248748010-f71dc670-cb58-4c09-82f3-fd8b1c7cb486.png) Do you have any idea what this could be?

@eoehen Try to remove `tools` folder and rebuild

2023-06-26 10:08 UTC, eoehen commented
> > @pascalberger Since rebasing, I can no longer run cake build locally. ![image](https://user-images.githubusercontent.com/49316770/248748010-f71dc670-cb58-4c09-82f3-fd8b1c7cb486.png) Do you have any idea what this could be?
> 
> @eoehen Try to remove `tools` folder and rebuild

Thank you.

2023-06-26 21:37 UTC, pascalberger reviewed
LGTM

2023-06-26 21:48 UTC, pascalberger approved these changes

2023-06-26 21:48 UTC, merged

2023-06-26 21:48 UTC, pascalberger commented
@eoehen your changes have been merged, thanks for your contribution 👍